### ISSUE TITLE
URL-decode resource names for HTTP API

### ISSUE THREAD

**Issue by kisunji** [hashicorp/consul#11258]
### Overview

Consul CLI has many [commands](https://www.consul.io/commands) that make HTTP calls to the local agent's HTTP API. 

Since some resource names are not URL safe, the caller must URL-encode certain characters. However, our handlers naively parse the URL as-is without a decode step, making it impossible to interact with resources that may have URL unsafe characters in their name or ID.

We should URL-decode path arguments when HTTP handlers try to parse the resource name ([example](https://github.com/hashicorp/consul/blob/cc310224aa24b3d7ed88e700be7fc95154dbbd9f/agent/agent_endpoint.go#L343-L344); can find others by searching for `strings.TrimPrefix(req.URL.Path`)

Related issues:
https://github.com/hashicorp/consul/issues/11191

### Correction
We previously assumed we also had to URL-encode corresponding HTTP calls in `api` module. This has been proven wrong in https://github.com/hashicorp/consul/pull/12184 - we only need to add decoding on handlers.

### Notes to contributors
Since the number of modified files is expected to be large, you are welcome to start work on a subset of endpoints and ask for feedback on your proposed solution/pattern before applying it to more places. 

Feel free to ask any questions and a member of our team will respond.

### Files with endpoints to cover (40 total)
- [x] ./agent/acl_endpoint.go (#11957)
- [x] ./agent/agent_endpoint.go (#11335)
- [x] ./agent/catalog_endpoint.go (#11957)
- [x] ./agent/config_endpoint.go (#11957)
- [x] ./agent/connect_ca_endpoint.go (no affected endpoints)
- [x] ./agent/coordinate_endpoint.go (#11957)
- [x] ./agent/discovery_chain_endpoint.go (#11957)
- [x] ./agent/event_endpoint.go (#12103)
- [x] ./agent/federation_state_endpoint.go (#12103)
- [x] ./agent/health_endpoint.go (#12103)
  - 3 endpoints were missed ([example](https://github.com/dttung2905/consul/blob/39b0d783d95de678156a80b5eca425d394e34f7c/agent/health_endpoint.go#L83
)) (#12297)
- [x] ./agent/intentions_endpoint.go (#12103)
- [x] ./agent/kvs_endpoint.go (#12103)
- [x] ./agent/operator_endpoint.go (no affected endpoints)
- [x] ./agent/prepared_query_endpoint.go (#12103)
- [x] ./agent/session_endpoint.go (#12103)
- [x] ./agent/snapshot_endpoint.go (no affected endpoints)
- [x] ./agent/status_endpoint.go (no affected endpoints)
- [x] ./agent/txn_endpoint.go (no affected endpoints)
- [x] ./agent/ui_endpoint.go (#12190)

**Comment by jkirschner-hashicorp** [comment]
Hi @littlestar642,

My understanding is that @krishnaindani has offered to work on this and will update us if that changes.

@krishnaindani : what's your status? I ask because @littlestar642 just submitted an initial PR with a possible approach (#11335). I want to make sure you are benefitting from each other's effort, not duplicating effort. You could perhaps coordinate on that PR / share your own thoughts.

**Comment by dttung2905** [comment]
Hi team, I also would like to help out on this too, like `agent.go` file for example ( if extra help is still needed ). 
I also see that @littlestar642 has opened an MR (#11335) with a generic function `getPathSuffixUnescaped` that could be reused  in other several places. Should I wait for his MR to be merged before applying to other files?

**Comment by jkirschner-hashicorp** [comment]
Hi @dttung2905,

Thanks for volunteering to help get this change applied to the many places it is needed! 

Please wait for MR #11335 to be merged before proceeding. We still have one final detail to sort out ([related to error handling](https://github.com/hashicorp/consul/pull/11335/files#r777575411)). I want to make sure we finalize the approach on that MR before applying anywhere else. Then, it should be straightforward to start creating MRs against the list of `*_endpoint.go` files in the issue description.

Are there specific files you'd like to volunteer for (once MR #11335 is approved and merged)?

**Comment by dttung2905** [comment]
Hi @jkirschner-hashicorp,
Sure, I will wait for the MR to be merged. I would like to help as many as possible, although I think its better to be broken down to several MR to easily track the changes. For the time being, I have made changes locally (yet to be committed) for the following files:
- acl_endpoint.go
- catalog_endpoint.go
- config_endpoint.go
- event_endpoint.go

Happy new year !

**Comment by jkirschner-hashicorp** [comment]
Thanks @dttung2905 - that's great! I'll reply here once it's merged.

If you happen to go through a file and find that it actually has no endpoints with parameters in the URL (which is unlikely, but possible), let me know so I can note that in the issue description / check it off in the list.

And I definitely agree that this should be broken down into multiple small-ish MRs so it's manageable for reviewers :)

**Comment by jkirschner-hashicorp** [comment]
@dttung2905 : MR #11335 has been merged. Please use it as a reference (for error handling, making changes to the API call, etc). Thanks again!

**Comment by fulviodenza** [comment]
a lot of files (such as ./agent/consul/catalog_endpoint.go) do not contain any route or something similar to the example pr. Should be considered as done or should we do something different from the pr 1/2/3/4?

**Comment by jkirschner-hashicorp** [comment]
@fulviodenza : write a comment indicating which files you've reviewed that don't need any updates. We'll double-check and mark complete (with a note) in the list in the issue description. Thanks for your help!

**Comment by kisunji** [comment]
@jkirschner-hashicorp @fulviodenza I don't think any of the `agent/consul/*_endpoint.go` are relevant for this issue. The HTTP endpoints are `agent/*_endpoint.go`

**Comment by dttung2905** [comment]
Thanks for the investigation. It seems like there are only a few files left. I can take up the rest if @fulviodenza has not worked on it

**Comment by dttung2905** [comment]
I just checked on the remaining files. There is no `strings.TrimPrefix(req.URL.Path)` being called. I also crossed check with the official doc and see that all of the methods do not have id parameters with id (example [/v1/connect/ca/roots](https://www.consul.io/api-docs/connect/ca) in `connect_ca_endpoint.go`
Could you help advise on what should we do in this case ?

**Comment by jkirschner-hashicorp** [comment]
@dttung2905 : sorry, your latest message slipped through the cracks for a bit.

@kisunji or I can double-check to make sure there are no resource names that need decoding in those files, then mark the ticket closed!

**Comment by jkirschner-hashicorp** [comment]
@dttung2905: it looks like 3 instances of `strings.TrimPrefix(req.URL.Path` were missed in `./agent/health_endpoint.go`:
- https://github.com/dttung2905/consul/blob/39b0d783d95de678156a80b5eca425d394e34f7c/agent/health_endpoint.go#L83
- https://github.com/dttung2905/consul/blob/39b0d783d95de678156a80b5eca425d394e34f7c/agent/health_endpoint.go#L131
- https://github.com/dttung2905/consul/blob/39b0d783d95de678156a80b5eca425d394e34f7c/agent/health_endpoint.go#L219

So we'll need to address those. (Unless there was some reason these were skipped in PR #12103 that I'm not aware of.)

I confirmed that no instances needed replacing in those remaining files, so they've been checked off the list!

**Comment by jkirschner-hashicorp** [comment]
Documentation added by https://github.com/hashicorp/consul/pull/12366

Marking closed!
