### ISSUE TITLE
Clean up child process handling

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2999]
This issue consolidates several similar issues with regards to child process handling. There are several areas in Consul where we spawn child processes but we have various issues:

* [x] `consul exec`
* [x] `consul lock`
* [x] `consul watch`
* [x] watch scripts
* [x] health check scripts

There are cases where we don't properly clean up and can leak child processes, or we don't handle signals properly. Some places we assume a shell, and others we don't. We should factor child process handling to be done in a uniform way (look at https://github.com/hashicorp/consul-template/tree/master/child, and maybe use that) and make sure that:

- [x] Signals are handled properly and passed along to child processes
- [x] Users can run without a shell if desired (we can have an optional shell to keep backward compatibility) (from https://github.com/hashicorp/consul/issues/1358)
- [x] Orphaned processes aren't left around
- [x] Quoting works on Windows (#1923)
- [x] `stdin` works on Windows (#1924)

**Comment by maxenglander** [comment]
@slackpad not sure if the following issue is covered by this master ticket, but something I've observed is that `consul watch` doesn't return the exit code of it's handler. E.g.

```sh
$ consul watch -prefix foo/bar sh -c 'exit 2'; echo $?
Error executing handler: exit status 2
1
```
This makes it difficult to integrate `consul watch` into a supervisor process that takes certain actions or not (e.g. restart or not) based on exit codes.

Let me know if it's not covered, I'll happily open a new ticket.

**Comment by slackpad** [comment]
Hi @maxenglander that's not captured here and is probably better on a separate issue. A similar change for `consul lock` was done under https://github.com/hashicorp/consul/issues/947.

**Comment by maxenglander** [comment]
Aha! Thanks @slackpad, opened #3526.
