### ISSUE TITLE
API key name cleanup / deprecations meta issue

### ISSUE THREAD

**Issue by pearkes** [hashicorp/consul#4033]
We have a number of planned changes and deprecations in API responses, specifically for key names. This issue is to track them in a central place to ensure they get into the next major release as breaking changes. These changes already support the alternative, we are just removing the legacy option. These changes would affect both the APIs and any static configuration.

- [ ] Check definition: `CheckID`will be replaced with `id`
- [ ] Service definition: `enableTagOverride` will be replaced with `enable_tag_override`
- [ ] Check definition: `script` will be replaced with `args`
- [ ] Telemetry: `consul.consul` metric prefix for backwards compatibility will be removed, only `consul.` will be sent, along with the removal of `enable_deprecated_names`
- [ ] Auto-join: Ensure we've swept up all instances of `retry-join-<provider>` from everywhere

It is possible to delay some of these changes if we consider them to be too impactful to users.
