### ISSUE TITLE
Release 1.6.0 Checklist

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#6373]
Checklist for things we need to do before cutting the final 1.6.0 release.

- [ ] Tag the sdk module
- [ ] Update the api module to use the tagged version of the sdk
- [ ] Tag the api module
- [ ] Update the main module to use the tagged version of the api.
- [ ] merge release/1-6 to master

**Comment by rboyer** [comment]
Would it make more sense to merge to master first, then do the tagging and go.mod updates?
