### ISSUE TITLE
Missing changelog entries

### ISSUE THREAD

**Issue by i0rek** [hashicorp/consul#7121]
* [x] `(Chris Piraino) * Fix segfault when removing both a service and associated check [[GH-7108](https://github.com/hashicorp/consul/pull/7108)]`
* [x] `(Chris Piraino) * Fix up formatting in sdk package [[GH-7109](https://github.com/hashicorp/consul/pull/7109)]`
* [x] `(David Yu) * Merge pull request #7102 from hashicorp/david-yu-patch-2 [[GH-7102](https://github.com/hashicorp/consul/pull/7102)]`
* [x] `(David Yu) * Merge pull request #7103 from hashicorp/david-yu-patch-3 [[GH-7103](https://github.com/hashicorp/consul/pull/7103)]`
* [x] `(David Yu) * Merge pull request #7104 from hashicorp/david-yu-patch-4 [[GH-7104](https://github.com/hashicorp/consul/pull/7104)]`
* [x] `(Hans Hasselberg) * agent: configurable MaxQueryTime and DefaultQueryTime. [[GH-3777](https://github.com/hashicorp/consul/pull/3777)]`
* [x] `(Hans Hasselberg) * agent: do not deregister service checks twice [[GH-6168](https://github.com/hashicorp/consul/pull/6168)]`
* [x] `(Hans Hasselberg) * agent: remove service sidecars in Agent.cleanupRegistration [[GH-7022](https://github.com/hashicorp/consul/pull/7022)]`
* [x] `(Hans Hasselberg) * agent: setup grpc server with auto_encrypt certs and add -https-port [[GH-7086](https://github.com/hashicorp/consul/pull/7086)]`
* [x] `(Hans Hasselberg) * auto_encrypt: set dns and ip san for k8s and provide configuration [[GH-6944](https://github.com/hashicorp/consul/pull/6944)]`
* [x] `(Hans Hasselberg) * connect: check if intermediate cert needs to be renewed. [[GH-6835](https://github.com/hashicorp/consul/pull/6835)]`
* [x] `(Hans Hasselberg) * connect: derive connect certificate serial numbers from a memdb index instead of the provider table max index [[GH-7011](https://github.com/hashicorp/consul/pull/7011)]`
* [x] `(Hans Hasselberg) * connect: ensure that updates to the secondary root CA configuration use the correct signing key ID values for comparison [[GH-7012](https://github.com/hashicorp/consul/pull/7012)]`
* [x] `(Hans Hasselberg) * connect: use correct subject key id for leaf certificates. [[GH-7091](https://github.com/hashicorp/consul/pull/7091)]`
* [x] `(Hans Hasselberg) * connect: use inline_string instead for envoy ca(#7024) [[GH-7024](https://github.com/hashicorp/consul/pull/7024)]`
* [x] `(Hans Hasselberg) * raft: increase raft notify buffer. [[GH-6863](https://github.com/hashicorp/consul/pull/6863)]`
* [x] `(Hans Hasselberg) * raft: update raft to v1.1.2 [[GH-7079](https://github.com/hashicorp/consul/pull/7079)]`
* [x] `(Hans Hasselberg) * rpc: log method when a server/server RPC call fails [[GH-4548](https://github.com/hashicorp/consul/pull/4548)]`
* [x] `(Hans Hasselberg) * tests: fix autopilot test [[GH-7092](https://github.com/hashicorp/consul/pull/7092)]`
* [x] `(Hans Hasselberg) * tests: fix zombie consul process while invoking TestServer.Stop() method in sdk/testutil in Windows [[GH-6032](https://github.com/hashicorp/consul/pull/6032)]`
* [x] `(Iryna Shustava) * Add docs about rolling out TLS on k8s [[GH-7096](https://github.com/hashicorp/consul/pull/7096)]`
* [x] `(Jack Pearkes) * Azure MSI for cloud auto-join [[GH-7000](https://github.com/hashicorp/consul/pull/7000)]`
* [x] `(Kit Patella) * .gitignore: cut IDE-specific entries, cleanup [[GH-7083](https://github.com/hashicorp/consul/pull/7083)]`
* [x] `(Kit Patella) * Small improvements to Connect docs [[GH-6910](https://github.com/hashicorp/consul/pull/6910)]`
* [x] `(Luke Kysow) * Merge pull request #6970 from hashicorp/k8s-docs-refactor [[GH-6970](https://github.com/hashicorp/consul/pull/6970)]`
* [x] `(Luke Kysow) * Merge pull request #6978 from hashicorp/docs/helm-move-bootstrapacls-under-global [[GH-6978](https://github.com/hashicorp/consul/pull/6978)]`
* [x] `(Matt Keeler) * Add support for dual stack IPv4/IPv6 network [[GH-6640](https://github.com/hashicorp/consul/pull/6640)]`
* [x] `(Matt Keeler) * AuthMethod updates to support alternate namespace logins [[GH-7029](https://github.com/hashicorp/consul/pull/7029)]`
* [x] `(Matt Keeler) * Move Session.CheckIDs into OSS only code. [[GH-6993](https://github.com/hashicorp/consul/pull/6993)]`
* [x] `(Matt Keeler) * Move where the service-resolver watch is done so that it happen… [[GH-7025](https://github.com/hashicorp/consul/pull/7025)]`
* [x] `(Paul Banks) * Add contributing dir with Config file checklist [[GH-7017](https://github.com/hashicorp/consul/pull/7017)]`
* [x] `(Paul Banks) * Fix TestAPI_DiscoveryChain_Get flake [[GH-7082](https://github.com/hashicorp/consul/pull/7082)]`
* [x] `(R.B. Boyer) * fix the submodule go.mod and go.sum files [[GH-7098](https://github.com/hashicorp/consul/pull/7098)]`
* [x] `(R.B. Boyer) * make TestCatalogNodes_Blocking less flaky [[GH-7074](https://github.com/hashicorp/consul/pull/7074)]`
* [x] `(Sarah Christoff) * Fix Namespace Typo [[GH-7030](https://github.com/hashicorp/consul/pull/7030)]`
* [x] `(danielehc) * Update docs to point to new learn guide [[GH-7003](https://github.com/hashicorp/consul/pull/7003)]`
* [x] `(danielehc) * added disclaimer about network segments due to Serf limitations [[GH-7004](https://github.com/hashicorp/consul/pull/7004)]`
* [x] `(kaitlincarter-hc) * New Connect guide for new users [[GH-6749](https://github.com/hashicorp/consul/pull/6749)]`
* [x] `(kaitlincarter-hc) * updating the ent docs to mention GCP [[GH-7001](https://github.com/hashicorp/consul/pull/7001)]`

range: 67c5c61be..48268e634 (aka v1.7.0-beta2..master)
command: git log --format="%s" 67c5c61be..48268e634 | string match -r "\#\d+"
echo $out | string split "$marker" | grep -v "docs:" | grep -v "test:" | grep -v "website:" | string trim | sort
