### ISSUE TITLE
Implement cached results with empty body and HTTP 304 semantics

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#7968]
Following my proposal https://github.com/hashicorp/consul/issues/3871

### Serialization is one of the biggest CPU usage for Consul in large DCs

In our large DCs, most of the time is spent serializing go structures of unmodified data, either because systems are polling for a very long time 10m, and then Consul returns the data, even with data is unmodified.

We used to have GRPC, which allowed us to divide by 3 the number of servers on large clusters because it actually did reduce very significantly the CPU spent serializing comparing to msgpack.

### Optimize CPU time spent on serialization of Servers

I was wondering if we could implement the following optimization:

1. Add an optional `X-Consul-Unmodified-Empty` header to queries perform to Consul
2. Forward a flag to Consul servers SendEmptyOnUnmodified in RPC query, flag that would be used with Hash and Index
3. When a query is processed on the server, if the flag is set, instead of serializing content back to Consul agent, return empty data with flag in response: `UnmodifiedData` => send just the meta of response, but not data within it
4. On the client, when this flag is present in the request, output normal headers, but return code HTTP `304 Not Modified`

I had a quick look and optimization looks quite straightforward to implement and would be a good optimization while waiting for streaming.

I would also be an optimization of SDKs as it would reduce quite a lot the processing time parsing always the same JSON on the client-side.

It would thus:
* Reduce *very* *very* significantly the load on Consul servers spent on serializing data
* Reduce very significantly the load on real-work servers (in our clusters, more than 95% of queries on health are unchanged)
* Reduce the CPU time spent by SDKs and programs parsing always the same data, and handle HTTP 304 directly

*Possible Alternative*: use cache directives as explained in https://github.com/hashicorp/consul/issues/3871 and do not use `X-Consul-Unmodified-Empty` (a bit riskier since it might break some unknown SDKs). 

### TODO

* [ ] apply the `NotModified` pattern to any relevant RPC endpoints that may return large results, along with a test for each. See #8215 for the first two.
* [ ] use the new query option in the `agent/cache`, and return the cached result when it sees `NotModified`
* [ ] figure out if and how we should expose this setting from the HTTP api

**Comment by pierresouchay** [comment]
After some work on #7974, I think using ETag + If-None-match might work safely, so the ugly header in request might be removed and replaced safely with header if-none-match. This would allow links to the API to be properly cached even by browsers while leveraging local cache client on the long term and reducing network usage and cpu spent serializing and deserialing data.

While it might sound a duplicate of streaming efforts, it will anyway give results on long term as it would improve SDK behavior and give effective performance gain when local agent has not the data locally in its cache (think load balancing on several consul agent not being present on localhost), so I think it deserves some attention and I suspect this will provide huge gains of scalability and performance for servers

**Comment by dnephin** [comment]
Thank you for raising this issue and demonstrating how valuable it could be! I've split this issue up into #10170 and #10171 which I am hoping will make it easier for us to prioritize, and track the work, and the value associated with each. I hope I've done an adequate job of capturing all the detail in those two issues. If I've missed anything please do leave a comment.

I'm going to close this issue since I hope we have captured everything in the other two.
